# Generated by Django 3.0.5 on 2020-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
                ('code', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
    ]
