# Generated by Django 3.0.5 on 2020-04-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200416_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='date',
        ),
    ]
