# Generated by Django 3.0.5 on 2020-04-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20200416_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=70, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Hospital')),
            ],
        ),
        migrations.RemoveField(
            model_name='recorddonation',
            name='itemdonated',
        ),
        migrations.RenameModel(
            old_name='ItemDonated',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='HospitalRequest',
        ),
        migrations.DeleteModel(
            name='RecordDonation',
        ),
        migrations.AddField(
            model_name='donation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
