# Generated by Django 3.0.5 on 2020-04-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
